# using socket config from https://www.theparsedweb.com/production-ready-setup-with-nginx-flask-and-postgres/
user www-data;
pid /run/nginx.pid;
worker_processes auto;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
    use               epoll;
}

http {
    include /etc/nginx/mime.types;
    sendfile           on;
    tcp_nopush         on;
    tcp_nodelay        on;
    keepalive_timeout  15;
    
    server {
        listen 80;
        listen [::]:80;
        server_name _;
        return 301 https://$host$request_uri;
    }
    
    server {
        listen 443 ssl default_server;

        proxy_intercept_errors off;

        ssl_certificate /etc/ssl/api_thirdeye_live.pem;
        ssl_certificate_key /etc/ssl/private/api_thirdeye_live.key;

        location / {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_pass          http://172.255.255.4:5000;          
        }

        location /image {
            alias /usr/share/nginx/html/image/;
            autoindex off;
        }

        location ~* ^/(quotes|all-authors|search|get-quote|post-quote|update-quote|delete-quote|author-quotes) {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_pass          http://172.255.255.4:5000;          
        }
        
        location /quote {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/quote;
        }

        location /quote/search {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/quote/search;
        }

        location /authors {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/authors;
        }

        location /admin/tokens {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/admin/tokens;
        }
        
        location /tarot/card {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/tarot/card;
        }
        
        location /tarot/deck {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/tarot/deck;
        }
        
        location /tarot/decks {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/tarot/decks;
        }
        
        location /tarot/spread {
            proxy_set_header    X-Forwarded-Proto $scheme;   
            proxy_set_header    Host $host;
            proxy_set_header    content-type "application/json";
            proxy_pass          http://172.255.255.3:8080/tarot/spread;
        }

    }

}

